enum SEMINAR_TYPE {
    OFFLINE=`OFFLINE`,
    ONLINE=`ONLINE`,
}

enum GENDER {
    MALE='MALE',
    FEMALE='FEMALE',
    HOMOSEXUAL='HOMOSEXUAL',
    NOT_SPECIFIED='NOT_SPECIFIED'
}

enum STATUS {
    ACTIVE='ACTIVE',
    INACTIVE='INACTIVE',
    DELETED='DELETED',
}

export {
    SEMINAR_TYPE,
    GENDER,
    STATUS
}